### Predicting formation enthalpies for solid solutions of Lanthanides Orthophosphates


In [22]:
import os
import sys
import inspect

print(sys.version)

currentdir = os.getcwd()
parentdir = os.path.dirname(currentdir)
grandparentdir = os.path.dirname(parentdir)

sys.path.insert(0, grandparentdir) 

3.9.6 (default, Nov 10 2023, 13:38:27) 
[Clang 15.0.0 (clang-1500.1.0.2.5)]


In [23]:
import read_data
import featureSpan
import lasso
import Utils
from sklearn.kernel_ridge import KernelRidge
from sklearn.model_selection import train_test_split, cross_val_score, ShuffleSplit
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error
import scipy.optimize
import pandas as pd
import seaborn as sns
import scipy.stats as ss
from sklearn.linear_model import Lasso
from itertools import combinations, product
import itertools
import math
import pandas as pd

## Xenotime + Monazite

#### Load data from files

In [24]:
list1M = read_data.readData("../../data/DATA_HE_monazite.dat")
print("Shape of List1M is {}".format(list1M.shape))
print(list1M)

Shape of List1M is (525, 4)
[[5.70000000e+01 5.80000000e+01 7.50000000e-01 1.29717527e-01]
 [5.70000000e+01 5.80000000e+01 6.25000000e-01 1.90974365e-01]
 [5.70000000e+01 5.80000000e+01 5.00000000e-01 1.92712564e-01]
 ...
 [7.00000000e+01 7.10000000e+01 5.00000000e-01 2.12444086e-02]
 [7.00000000e+01 7.10000000e+01 3.75000000e-01 2.22639048e-02]
 [7.00000000e+01 7.10000000e+01 2.50000000e-01 2.09098752e-02]]


In [25]:
list2M = read_data.readCSVData("../../data/Data_Ln-monazite.csv", Volume=False)
print("Shape of List2M is {}".format(list2M.shape))
print((list2M))

Shape of List2M is (15, 8)
[[ 57.      138.90547  19.1773  139.1      11.        1.1      49.95
    1.216  ]
 [ 58.      140.116    20.198   146.5      12.        1.12     36.758
    1.196  ]
 [ 59.      140.90765  21.624   150.1      12.3       1.13     38.98
    1.179  ]
 [ 60.      144.242    22.1     154.1      12.95      1.14     40.41
    1.163  ]
 [ 61.      145.       22.3     157.4      13.6       1.13     41.1
    1.144  ]
 [ 62.      150.36     23.4     160.3      14.25      1.17     41.4
    1.132  ]
 [ 63.      151.964    24.92    163.1      14.9       1.2      42.7
    1.12   ]
 [ 64.      157.25     20.63    165.2      15.9       1.2      44.
    1.107  ]
 [ 65.      158.92535  21.91    164.5      16.2       1.1      39.79
    1.095  ]
 [ 66.      162.5      22.8     165.4      16.85      1.22     41.47
    1.083  ]
 [ 67.      164.93032  22.84    167.3      17.5       1.23     42.5
    1.072  ]
 [ 68.      167.259    22.74    169.1      18.15      1.24     42.7
    1.06

In [26]:
list1X = read_data.readData("../../data/DATA_HE_xenotime.dat")
print("Shape of List1X is {}".format(list1X.shape))
print(list1X)

Shape of List1X is (525, 4)
[[5.70000000e+01 5.80000000e+01 7.50000000e-01 2.31598225e-01]
 [5.70000000e+01 5.80000000e+01 6.25000000e-01 2.78958493e-01]
 [5.70000000e+01 5.80000000e+01 5.00000000e-01 2.97583757e-01]
 ...
 [7.00000000e+01 7.10000000e+01 5.00000000e-01 7.77590152e-02]
 [7.00000000e+01 7.10000000e+01 3.75000000e-01 7.09266168e-02]
 [7.00000000e+01 7.10000000e+01 2.50000000e-01 5.91211365e-02]]


In [27]:
list2X = read_data.readCSVData("../../data/Data_Ln-xenotime.csv", material = "xenotime", Volume=False)
print("Shape of List2X is {}".format(list2X.shape))
print((list2X))

Shape of List2X is (15, 8)
[[ 57.      138.90547  19.1773   91.7      11.        1.1      49.95
    1.16   ]
 [ 58.      140.116    20.198    99.73     12.        1.12     36.758
    1.143  ]
 [ 59.      140.90765  21.624   112.27     12.3       1.13     38.98
    1.126  ]
 [ 60.      144.242    22.1     120.19     12.95      1.14     40.41
    1.109  ]
 [ 61.      145.       22.3     127.26     13.6       1.13     41.1
    1.093  ]
 [ 62.      150.36     23.4     137.16     14.25      1.17     41.4
    1.079  ]
 [ 63.      151.964    24.92    143.83     14.9       1.2      42.7
    1.066  ]
 [ 64.      157.25     20.63    149.42     15.9       1.2      44.
    1.053  ]
 [ 65.      158.92535  21.91    156.33     16.2       1.1      39.79
    1.04   ]
 [ 66.      162.5      22.8     163.       16.85      1.22     41.47
    1.027  ]
 [ 67.      164.93032  22.84    169.12     17.5       1.23     42.5
    1.015  ]
 [ 68.      167.259    22.74    177.09     18.15      1.24     42.7
    1.00

#### Generated Elemental Training/Testing sets from loaded data

In [28]:
def generateFeatures_full2(HEList, featureList):
    X = []
    Y = []
    
    for i in range(len(HEList)):
        Y.append(HEList[i][3])
        
        x = HEList[i][2]
        X1 = featureList[int(HEList[i][0]-57)]
        X2 = featureList[int(HEList[i][1]-57)]

        #X.append(np.concatenate((np.array([x, 1/x, x * x, 1 / (x * x), 1-x, 1/(1-x), (1-x) * (1-x), 1/( (1-x) * (1-x))]), np.array([abs(X1-X2)/2.0, 2.0 / (abs(X1-X2)), (X1 + X2) / 2.0, 2.0 / (X1 + X2)]).flatten())))
        mfeatures = np.array([x, 1/x, x * x, 1 / (x * x), 1-x, 1/(1-x), (1-x) * (1-x), 1/( (1-x) * (1-x))])
        
        f1 = []
        f2 = []
        f3 = []
        f4 = []
        
        for j in range(len(X1)-3):
            f1.append([abs(X1[j]-X2[j])/2.0])
            f2.append([2.0/abs(X1[j]-X2[j])])
            f3.append([(X1[j] + X2[j]) / 2.0])
            f4.append([2.0 / (X1[j] + X2[j])])
            
        #rint(f3)
        #print(np.asarray(f3).flatten())
    
        #print(np.concatenate((mfeatures, np.asarray(f1).flatten(), np.asarray(f3).flatten())))
              
        f5 = []
        f6 = []
        f7 = []
        
        for j in range(5,7):
            f5.append([abs(X1[j]-X2[j])/2.0])
            f6.append([(X1[j] + X2[j]) / 2.0])
            f7.append([2.0 / (X1[j] + X2[j])])            
            
        f8 = []
        f9 = []
        f10 = []
        f11 = []
        f12 = []
        f13 = []
        f14 = []
        f15 = []
        f16 = []
        f17 = []
        f18 = []
        f19 = []
        
        #skip R
        for j in range(7,len(X1)):
            f8.append([abs(X1[j]-X2[j])/2.0])
            f9.append([2.0/abs(X1[j]-X2[j])])
            f10.append([(X1[j] + X2[j]) / 2.0])
            f11.append([2.0 / (X1[j] + X2[j])])
            f12.append([pow(abs(X1[j]-X2[j])/2.0,2)])
            f13.append([pow(2.0/abs(X1[j]-X2[j]),2)])
            f14.append([pow((X1[j] + X2[j]) / 2.0,2)])
            f15.append([pow(2.0 / (X1[j] + X2[j]),2)])
            f16.append([pow(abs(X1[j]-X2[j])/2.0,3)])
            f17.append([pow(2.0/abs(X1[j]-X2[j]),3)])
            f18.append([pow((X1[j] + X2[j]) / 2.0,3)])
            f19.append([pow(2.0 / (X1[j] + X2[j]),3)])
            
        
        X.append(np.concatenate((mfeatures, np.asarray(f1).flatten(),  np.asarray(f2).flatten(),  np.asarray(f3).flatten(), np.asarray(f4).flatten(), np.asarray(f5).flatten(), np.asarray(f6).flatten(),np.asarray(f7).flatten(),np.asarray(f8).flatten(),np.asarray(f9).flatten(),np.asarray(f10).flatten(),np.asarray(f11).flatten(),np.asarray(f12).flatten(),np.asarray(f13).flatten(),np.asarray(f14).flatten(),np.asarray(f15).flatten(),np.asarray(f16).flatten(),np.asarray(f17).flatten(),np.asarray(f18).flatten(),np.asarray(f19).flatten()     )))
            
    return X, Y

In [29]:
listXM, listYM = generateFeatures_full2(list1M, list2M)
XM = np.asarray(listXM)
YM = np.asarray(listYM)
print(XM.shape)
print(YM.shape)

listXX, listYX = generateFeatures_full2(list1X, list2X)
XX = np.asarray(listXX)
YX = np.asarray(listYX)
print(XM.shape)
print(YM.shape)

X = np.concatenate((XM, XX), axis=0)
Y = np.concatenate((YM, YX), axis=0)
print(X.shape)
print(Y.shape)

elemental_list = ["m", "1/m", "m^2", "(1/m)^2", "(1-m)", "1/(1-m)", "(1-m)^2", "(1/(1-m))^2", "[AD:Z]", "[AD:M]", "[AD:IP2]", "[AD:Young]", "[AD:Charge]",  "(1/[AD:Z])", "(1/[AD:M])", "(1/[AD:IP2])", "(1/[AD:Young])", "(1/[AD:Charge])",  "[AM:Z]", "[AM:M]", "[AM:IP2]", "[AM:Young]", "[AM:Charge]",  "(1/[AM:Z])", "(1/[AM:M])", "(1/[AM:IP2])", "(1/[AM:Young])", "(1/[AM:Charge])", "[AD:electronegativity]", "[AD:IP3]", "[AM:electronegativity]", "[AM:IP3]","(1/[AM:electronegativity])", "(1/[AM:IP3])" ,    "[AD:R]", "(1/[AD:R])","[AM:R]","(1/[AM:R])",   "([AD:R])^2", "(1/[AD:R])^2" , "([AM:R])^2","(1/[AM:R])^2",    "([AD:R])^3", "(1/[AD:R])^3", "([AM:R])^3", "(1/[AM:R])^3"         ]
print(len(elemental_list))
print(elemental_list)
m, n = X.shape

elemental_features = []

for i in elemental_list:
    elemental_features.append("("+i+")")
        
print("The elemental features are: \n {}".format(elemental_features))

(525, 46)
(525,)
(525, 46)
(525,)
(1050, 46)
(1050,)
46
['m', '1/m', 'm^2', '(1/m)^2', '(1-m)', '1/(1-m)', '(1-m)^2', '(1/(1-m))^2', '[AD:Z]', '[AD:M]', '[AD:IP2]', '[AD:Young]', '[AD:Charge]', '(1/[AD:Z])', '(1/[AD:M])', '(1/[AD:IP2])', '(1/[AD:Young])', '(1/[AD:Charge])', '[AM:Z]', '[AM:M]', '[AM:IP2]', '[AM:Young]', '[AM:Charge]', '(1/[AM:Z])', '(1/[AM:M])', '(1/[AM:IP2])', '(1/[AM:Young])', '(1/[AM:Charge])', '[AD:electronegativity]', '[AD:IP3]', '[AM:electronegativity]', '[AM:IP3]', '(1/[AM:electronegativity])', '(1/[AM:IP3])', '[AD:R]', '(1/[AD:R])', '[AM:R]', '(1/[AM:R])', '([AD:R])^2', '(1/[AD:R])^2', '([AM:R])^2', '(1/[AM:R])^2', '([AD:R])^3', '(1/[AD:R])^3', '([AM:R])^3', '(1/[AM:R])^3']
The elemental features are: 
 ['(m)', '(1/m)', '(m^2)', '((1/m)^2)', '((1-m))', '(1/(1-m))', '((1-m)^2)', '((1/(1-m))^2)', '([AD:Z])', '([AD:M])', '([AD:IP2])', '([AD:Young])', '([AD:Charge])', '((1/[AD:Z]))', '((1/[AD:M]))', '((1/[AD:IP2]))', '((1/[AD:Young]))', '((1/[AD:Charge]))', '([AM:Z]

In [30]:
dfX = pd.DataFrame(data=X, columns=elemental_features)

new_features=[]
new_columns = []

for i in range(n):
    for j in range(i):
        new_features.append(elemental_features[i]+"*"+elemental_features[j])
        new_columns.append(dfX[elemental_features[i]].values * dfX[elemental_features[j]].values)


for i in range(n):
    for j in range(i):
        for k in range(j):
            new_features.append(elemental_features[i]+"*"+elemental_features[j]+"*"+elemental_features[k])
            new_columns.append(dfX[elemental_features[i]] * dfX[elemental_features[j]] * dfX[elemental_features[k]])
            
            
new_columns = np.asarray(new_columns)
dfX = pd.concat(
    [
        dfX,
        pd.DataFrame(
            new_columns.T, 
            index=dfX.index, 
            columns=new_features
        )
    ], axis=1
)

dfX.head()

dfX.std() == 0
dfX=dfX.loc[:, dfX.std() > 0]
dfX.head()

(m)     (1/m)     (m^2)  ((1/m)^2)  ((1-m))  (1/(1-m))  ((1-m)^2)  \
0  0.750  1.333333  0.562500   1.777778    0.250   4.000000   0.062500   
1  0.625  1.600000  0.390625   2.560000    0.375   2.666667   0.140625   
2  0.500  2.000000  0.250000   4.000000    0.500   2.000000   0.250000   
3  0.375  2.666667  0.140625   7.111111    0.625   1.600000   0.390625   
4  0.250  4.000000  0.062500  16.000000    0.750   1.333333   0.562500   

   ((1/(1-m))^2)  ([AD:Z])  ([AD:M])  ...  \
0      16.000000       0.5  0.605265  ...   
1       7.111111       0.5  0.605265  ...   
2       4.000000       0.5  0.605265  ...   
3       2.560000       0.5  0.605265  ...   
4       1.777778       0.5  0.605265  ...   

   ((1/[AM:R])^3)*(([AM:R])^3)*([AD:R])  \
0                                  0.01   
1                                  0.01   
2                                  0.01   
3                                  0.01   
4                                  0.01   

   ((1/[AM:R])^3)*(([AM:R])^3)*((1/[AD:R]))  \
0                                     100.0   
1                                     100.0   
2                                     100.0   
3                                     100.0   
4                                     100.0   

   ((1/[AM:R])^3)*(([AM:R])^3)*([AM:R])  \
0                                 1.206   
1                                 1.206   
2                                 1.206   
3                                 1.206   
4                                 1.206   

   ((1/[AM:R])^3)*(([AM:R])^3)*((1/[AM:R]))  \
0                                  0.829187   
1                                  0.829187   
2                                  0.829187   
3                                  0.829187   
4                                  0.829187   

   ((1/[AM:R])^3)*(([AM:R])^3)*(([AD:R])^2)  \
0                                    0.0001   
1                                    0.0001   
2                                    0.0001   
3                                    0.0001   
4                                    0.0001   

   ((1/[AM:R])^3)*(([AM:R])^3)*((1/[AD:R])^2)  \
0                                     10000.0   
1                                     10000.0   
2                                     10000.0   
3                                     10000.0   
4                                     10000.0   

   ((1/[AM:R])^3)*(([AM:R])^3)*(([AM:R])^2)  \
0                                  1.454436   
1                                  1.454436   
2                                  1.454436   
3                                  1.454436   
4                                  1.454436   

   ((1/[AM:R])^3)*(([AM:R])^3)*((1/[AM:R])^2)  \
0                                    0.687552   
1                                    0.687552   
2                                    0.687552   
3                                    0.687552   
4                                    0.687552   

   ((1/[AM:R])^3)*(([AM:R])^3)*(([AD:R])^3)  \
0                                  0.000001   
1                                  0.000001   
2                                  0.000001   
3                                  0.000001   
4                                  0.000001   

   ((1/[AM:R])^3)*(([AM:R])^3)*((1/[AD:R])^3)  
0                                   1000000.0  
1                                   1000000.0  
2                                   1000000.0  
3                                   1000000.0  
4                                   1000000.0  

[5 rows x 16255 columns]

In [31]:
print(len(dfX.columns.values))
np.array(dfX.columns.values)

16255


array(['(m)', '(1/m)', '(m^2)', ...,
       '((1/[AM:R])^3)*(([AM:R])^3)*((1/[AM:R])^2)',
       '((1/[AM:R])^3)*(([AM:R])^3)*(([AD:R])^3)',
       '((1/[AM:R])^3)*(([AM:R])^3)*((1/[AD:R])^3)'], dtype=object)

In [32]:
def LassoFit(lmb, X, Y, max_iter=100000, standardization = True):
    
    scaler = StandardScaler()
    scaler.fit(X)
    X_standardized = scaler.transform(X)
    lasso =  Lasso(alpha=lmb, max_iter=max_iter)
    lasso.fit(X_standardized, Y.copy())
    coef =  lasso.coef_
    selected_indices = coef.nonzero()[0]
    selected_features = np.array(dfX.columns.values)[selected_indices]
    Y_predict = lasso.predict(X_standardized)
    MAE, MSE, MAPE = Utils.compute_error(Y.copy(), Y_predict)
        
    return coef, selected_indices, selected_features, MAE, MSE, MAPE

LassoFit(0.01, dfX, Y)

(array([ 0., -0.,  0., ..., -0.,  0.,  0.]),
 array([ 1257,  2552,  4428,  5094,  5117,  5647,  5987,  7303,  7370,
         7395,  7436,  7535,  8533,  8675,  9361,  9528,  9570,  9613,
         9638,  9987, 10417, 12295, 12657, 12682, 12944, 13503, 14707,
        15271, 15282, 15839]),
 array(['([AD:Young])*((1-m)^2)*(m^2)',
        '([AM:Young])*((1/[AD:Charge]))*([AD:Young])',
        '([AD:electronegativity])*([AD:Charge])*([AD:Young])',
        '([AD:IP3])*((1/[AM:Charge]))*((1/[AD:M]))',
        '([AD:IP3])*([AD:electronegativity])*([AD:IP2])',
        '([AM:IP3])*([AD:Charge])*([AD:Young])',
        '([AM:IP3])*([AD:IP3])*([AD:Young])',
        '([AD:R])*([AM:Charge])*((1/[AD:Z]))',
        '([AD:R])*((1/[AM:IP2]))*([AD:Young])',
        '([AD:R])*((1/[AM:Young]))*([AD:Young])',
        '([AD:R])*((1/[AM:Charge]))*((1/[AM:Young]))',
        '([AD:R])*([AM:IP3])*([AD:Young])',
        '([AM:R])*((1/[AM:IP2]))*([AM:Z])',
        '([AM:R])*([AM:electronegativity])*((1/[AM:IP2]))',

In [33]:
#### Define a function which fits Lasso to have no more nonzero coefficients than a given threshold 
def LassoSelect(X, Y, min, max, step, threshold, standardization = True):
    
    scaler = StandardScaler()
    scaler.fit(X)
    X_standardized = scaler.transform(X)
        
    found = False
    for lmbda in np.arange (min, max, step):
        coef, selected_indices, selected_features, MAE, MSE, MAPE = LassoFit(lmbda, X.copy(), Y.copy())
        if len(selected_indices) <= threshold:
            found = True
            break
    
    if found:
        print("FOUND with threshold: {}".format(threshold))
        print("Lambda: {}, nnz: {}, MAE: {}, MSE: {}, MAPE: {}".format(lmbda, len(selected_indices), MAE, MSE, MAPE))
            
    else:
        print("NOT FOUND with threshold: {}".format(threshold))
        print("Closest are: ")
        print("Lambda: {}, nnz: {}, MAE: {}, MSE: {}, MAPE: {}".format(lmbda, len(selected_indices), MAE, MSE, MAPE))
     
    X_reduced = X[selected_features]
    
    return X_reduced


X_reduced = LassoSelect(dfX, Y, 0.021, 0.121, 0.005, 30)
X_reduced.head()

FOUND with threshold: 30
Lambda: 0.021, nnz: 18, MAE: 0.09678366540568344, MSE: 0.020700438434153666, MAPE: 0.2606690148558449


([AD:Young])*((1-m)^2)*(m^2)  \
0                      0.130078   
1                      0.203247   
2                      0.231250   
3                      0.203247   
4                      0.130078   

   ([AD:electronegativity])*([AD:Charge])*([AD:Young])  \
0                                             0.0185     
1                                             0.0185     
2                                             0.0185     
3                                             0.0185     
4                                             0.0185     

   ([AD:IP3])*([AD:electronegativity])*([AD:IP2])  \
0                                        0.033663   
1                                        0.033663   
2                                        0.033663   
3                                        0.033663   
4                                        0.033663   

   ([AM:IP3])*([AD:Charge])*([AD:Young])  ([AM:IP3])*([AD:IP3])*([AD:Young])  \
0                                80.2049                         1058.063041   
1                                80.2049                         1058.063041   
2                                80.2049                         1058.063041   
3                                80.2049                         1058.063041   
4                                80.2049                         1058.063041   

   ([AD:R])*((1/[AM:IP2]))*([AD:Young])  \
0                              0.001879   
1                              0.001879   
2                              0.001879   
3                              0.001879   
4                              0.001879   

   ([AD:R])*((1/[AM:Young]))*([AD:Young])  \
0                                0.000259   
1                                0.000259   
2                                0.000259   
3                                0.000259   
4                                0.000259   

   ([AD:R])*((1/[AM:Charge]))*([AD:Young])  \
0                                 0.003217   
1                                 0.003217   
2                                 0.003217   
3                                 0.003217   
4                                 0.003217   

   ([AD:R])*((1/[AM:Charge]))*((1/[AM:IP2]))  \
0                                   0.000044   
1                                   0.000044   
2                                   0.000044   
3                                   0.000044   
4                                   0.000044   

   ([AD:R])*((1/[AM:Charge]))*((1/[AM:Young]))  \
0                                     0.000006   
1                                     0.000006   
2                                     0.000006   
3                                     0.000006   
4                                     0.000006   

   ([AD:R])*([AM:IP3])*([AD:Young])  ([AM:R])*((1/[AM:IP2]))*([AM:Z])  \
0                          1.604098                          3.522259   
1                          1.604098                          3.522259   
2                          1.604098                          3.522259   
3                          1.604098                          3.522259   
4                          1.604098                          3.522259   

   ((1/[AM:R]))*((1/[AM:electronegativity]))*([AM:IP2])  \
0                                          14.706983      
1                                          14.706983      
2                                          14.706983      
3                                          14.706983      
4                                          14.706983      

   (([AD:R])^2)*((1-m)^2)*(m^2)  (([AD:R])^2)*([AD:Young])*((1-m))  \
0                      0.000004                           0.000093   
1                      0.000005                           0.000139   
2                      0.000006                           0.000185   
3                      0.000005                           0.000231   
4                      0.000004                           0.000278   

   (([AD:R])^2)*((1/[AD:M]))*([

In [34]:
def LassoL0(X, Y, nnz):    
    nr, nc = X.shape
    X = np.column_stack((X, np.ones(nr)))
    se_min = np.inner(Y, Y)
    coef_min, permu_min = None, None
    for permu in combinations(range(nc), nnz):
        X_ls = X[:, permu + (-1,)]
        coef, se, __1, __2 = np.linalg.lstsq(X_ls, Y, rcond=-1)
        try:
            if se[0] < se_min: 
                se_min = se[0]
                coef_min, permu_min = coef, permu
        except:
            pass
        
    return coef_min, permu_min

In [35]:
def LassoL0Fit(X_reduced, Y, nnz, log=True):
    
    scaler = StandardScaler()
    scaler.fit(X_reduced)
    X_std = scaler.transform(X_reduced)
    
    nr, nc = X_reduced.shape
   
    coefficients, selected_indices = LassoL0(X_std, Y, nnz)
   
    coefficients = np.array(coefficients)
    selected_indices = np.array(selected_indices)
    feature_reduced = np.array(X_reduced.columns.values)
    feature_list_selected = feature_reduced[selected_indices]
    
    X_selected = X_reduced[feature_list_selected]

    mean_selected = X_selected.mean()
    std_selected = X_selected.std()

    
    if log:
        print("Lasso: selected coefficients are: {}".format(coefficients))
        print("Lasso: selected features are: {}".format(feature_list_selected))
        
    #-mean/std
    mean_std = []
    for i in range(len(selected_indices)):
        mean_std.append(coefficients[i] * mean_selected[i]/std_selected[i])
 
    sum_mean_std = sum(mean_std)

    for i in range(len(selected_indices)):
        coefficients[i] = coefficients[i] / std_selected[i]

    
    coefficients[len(selected_indices)] -= sum_mean_std
    
    function = str(coefficients[0])+" * "+feature_list_selected[0]
    
    for i in range(1, len(selected_indices)):
        if coefficients[i] >= 0:
            function += " + " + str(coefficients[i])+" * "+feature_list_selected[i]
        else:
            function += " - " + str(abs(coefficients[i]))+" * "+feature_list_selected[i]

    
    if coefficients[len(selected_indices)] >= 0:
        function += " + " + str(coefficients[len(selected_indices)])
    else:
        function += " - " + str(abs(coefficients[len(selected_indices)]))
    
    if log:
        print("Constructed function is: {}".format(function))

    X_selected = np.column_stack((X_selected, np.ones(X_selected.shape[0])))
    Y_predict = X_selected[:,0] * coefficients[0]

    for i in range(1,len(selected_indices)+1):
        Y_predict = Y_predict + X_selected[:,i] * coefficients[i]
    
    if log:
        Utils.print_error(Y.copy(),Y_predict,"Lasso L0: {} coef".format(nnz))
    
    return Y_predict, coefficients, selected_indices

In [36]:
LassoL0Fit(X_reduced, Y.copy(), 1);

Lasso: selected coefficients are: [2.94143833 2.41207633]
Lasso: selected features are: ['([AD:R])*((1/[AM:IP2]))*([AD:Young])']
Constructed function is: 72.54971769773363 * ([AD:R])*((1/[AM:IP2]))*([AD:Young]) + 0.36613067897391494
Lasso L0: 1 coef
Mean absolute error: 0.5581998945977972
Mean squared error: 0.6803445299264388
Mean absolute percentage error: 1.914182354422858


/var/folders/_0/q128s8pd1lb95k4pms0qlpw40000gn/T/ipykernel_19981/1248470983.py:29: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mean_std.append(coefficients[i] * mean_selected[i]/std_selected[i])
/var/folders/_0/q128s8pd1lb95k4pms0qlpw40000gn/T/ipykernel_19981/1248470983.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  coefficients[i] = coefficients[i] / std_selected[i]


In [37]:
LassoL0Fit(X_reduced, Y.copy(), 2);

Lasso: selected coefficients are: [1.85757865 1.37657418 2.41207633]
Lasso: selected features are: ['([AD:R])*((1/[AM:Young]))*([AD:Young])' '(([AD:R])^2)*((1-m)^2)*(m^2)']
Constructed function is: 302.26914897675937 * ([AD:R])*((1/[AM:Young]))*([AD:Young]) + 14068.242396210326 * (([AD:R])^2)*((1-m)^2)*(m^2) - 0.027106328310655403
Lasso L0: 2 coef
Mean absolute error: 0.1374801899188061
Mean squared error: 0.05261869188356983
Mean absolute percentage error: 0.15489637178594307


/var/folders/_0/q128s8pd1lb95k4pms0qlpw40000gn/T/ipykernel_19981/1248470983.py:29: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mean_std.append(coefficients[i] * mean_selected[i]/std_selected[i])
/var/folders/_0/q128s8pd1lb95k4pms0qlpw40000gn/T/ipykernel_19981/1248470983.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  coefficients[i] = coefficients[i] / std_selected[i]


In [38]:
LassoL0Fit(X_reduced, Y.copy(), 3);

Lasso: selected coefficients are: [1.64328847 1.34795712 0.26158242 2.41207633]
Lasso: selected features are: ['([AD:R])*((1/[AM:Young]))*([AD:Young])' '(([AD:R])^2)*((1-m)^2)*(m^2)'
 '(([AD:R])^2)*([AD:Young])*((1-m))']
Constructed function is: 267.3993948486992 * ([AD:R])*((1/[AM:Young]))*([AD:Young]) + 13775.783196452918 * (([AD:R])^2)*((1-m)^2)*(m^2) + 7.138662347707119 * (([AD:R])^2)*([AD:Young])*((1-m)) + 0.01358875661088721
Lasso L0: 3 coef
Mean absolute error: 0.12491592955817257
Mean squared error: 0.04036751389578485
Mean absolute percentage error: 0.16507716165954384


/var/folders/_0/q128s8pd1lb95k4pms0qlpw40000gn/T/ipykernel_19981/1248470983.py:29: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mean_std.append(coefficients[i] * mean_selected[i]/std_selected[i])
/var/folders/_0/q128s8pd1lb95k4pms0qlpw40000gn/T/ipykernel_19981/1248470983.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  coefficients[i] = coefficients[i] / std_selected[i]


In [39]:
LassoL0Fit(X_reduced, Y.copy(), 4);

Lasso: selected coefficients are: [0.93022558 1.28086405 0.21664949 0.81313569 2.41207633]
Lasso: selected features are: ['([AD:R])*((1/[AM:IP2]))*([AD:Young])' '(([AD:R])^2)*((1-m)^2)*(m^2)'
 '(([AD:R])^2)*([AD:Young])*((1-m))'
 '(([AD:R])^2)*((1/[AD:M]))*([AD:Young])']
Constructed function is: 22.943742313096827 * ([AD:R])*((1/[AM:IP2]))*([AD:Young]) + 13090.108833490875 * (([AD:R])^2)*((1-m)^2)*(m^2) + 5.912429087601156 * (([AD:R])^2)*([AD:Young])*((1-m)) + 185.53630546959982 * (([AD:R])^2)*((1/[AD:M]))*([AD:Young]) + 0.004005798151936801
Lasso L0: 4 coef
Mean absolute error: 0.11105245604238913
Mean squared error: 0.03290229120572359
Mean absolute percentage error: 0.1389640608047862


/var/folders/_0/q128s8pd1lb95k4pms0qlpw40000gn/T/ipykernel_19981/1248470983.py:29: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mean_std.append(coefficients[i] * mean_selected[i]/std_selected[i])
/var/folders/_0/q128s8pd1lb95k4pms0qlpw40000gn/T/ipykernel_19981/1248470983.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  coefficients[i] = coefficients[i] / std_selected[i]


In [40]:
LassoL0Fit(X_reduced, Y.copy(), 5);

Lasso: selected coefficients are: [0.18927067 0.28013269 1.27718627 1.26980789 0.27017689 2.41207633]
Lasso: selected features are: ['([AD:Young])*((1-m)^2)*(m^2)' '([AM:IP3])*([AD:IP3])*([AD:Young])'
 '([AD:R])*([AM:IP3])*([AD:Young])' '(([AD:R])^2)*((1-m)^2)*(m^2)'
 '(([AD:R])^2)*([AD:Young])*((1-m))']
Constructed function is: 0.3198681951645182 * ([AD:Young])*((1-m)^2)*(m^2) + 0.00016804681561082894 * ([AM:IP3])*([AD:IP3])*([AD:Young]) + 0.03355228385944727 * ([AD:R])*([AM:IP3])*([AD:Young]) + 12977.117729208518 * (([AD:R])^2)*((1-m)^2)*(m^2) + 7.373207805839338 * (([AD:R])^2)*([AD:Young])*((1-m)) - 0.0603270238535587
Lasso L0: 5 coef
Mean absolute error: 0.10751704399634797
Mean squared error: 0.02607541897634145
Mean absolute percentage error: 0.21804401794930306


/var/folders/_0/q128s8pd1lb95k4pms0qlpw40000gn/T/ipykernel_19981/1248470983.py:29: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mean_std.append(coefficients[i] * mean_selected[i]/std_selected[i])
/var/folders/_0/q128s8pd1lb95k4pms0qlpw40000gn/T/ipykernel_19981/1248470983.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  coefficients[i] = coefficients[i] / std_selected[i]
